version: '3'
services:
  node:
    build:
      context: ./
      dockerfile: ./Docker/node/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./api/:/usr/src/app
      - /usr/src/app/node_modules # Remove this if you have pure JS dependencies
    depends_on:
      - db
  db:
    build: ./Docker/postgre
    ports:
      - "5432:5432"
