version: '3'
services:
  node:
    build:
      context: ./
      dockerfile: ./Docker/node/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./api/:/usr/src/app
    depends_on:
      - db
    networks:
      - default
  db:
    build: ./Docker/postgre
    ports:
      - "5432:5432"
    networks:
      - default

networks:
  default:
