version: '3'
services:
  node:
    build:
      context: ./
      dockerfile: ./Docker/node/Dockerfile
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/user/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
  db:
    build: ./Docker/postgre
    ports:
      - "5432:5432"
