version: '3'
services:
  node:
    build:
      context: ./
      dockerfile: ./Docker/node/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./api/:/usr/src/app
      - /usr/src/app/node_modules/bcrypt/
    depends_on:
      - db
    networks:
      - default
  view:
    image: node:latest
    working_dir: /app
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./front:/app
    command: bash -c "npm install esbuild && npm run dev"
    ports:
      - 8080:8080
  db:
    build: ./Docker/postgre
    ports:
      - "5432:5432"
    networks:
      - default

networks:
  default:
